openapi: 3.0.0
info:
  title: Rakuten API
  version: '1.0'
  contact:
    name: Rakuten
  description: Rakuten API
  termsOfService: 'https://webservice.rakuten.co.jp/api/bookstotalsearch/'
servers:
  - url: 'https://app.rakuten.co.jp/services/api'
paths:
  /BooksTotal/Search/20170404:
    get:
      summary: getBooksTotal
      operationId: getBooksTotal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: string
                  page:
                    type: string
                  first:
                    type: string
                  last:
                    type: string
                  hits:
                    type: string
                  carrier:
                    type: string
                  pageCount:
                    type: string
                  items:
                    type: array
                    items: {}
      description: 楽天本検索APIエンドポイント
      parameters:
        - schema:
            type: string
            default: '1035252894012359396'
          in: query
          name: applicationId
          required: true
          description: ''
        - schema:
            type: string
          in: query
          name: affiliateId
        - schema:
            type: string
            default: json
          in: query
          name: format
        - schema:
            type: string
          in: query
          name: keyword
        - schema:
            type: string
            default: '000'
          in: query
          name: booksGenreId
          required: true
        - schema:
            type: string
          in: query
          name: isbnjan
        - schema:
            type: integer
            default: '30'
          in: query
          name: hits
        - schema:
            type: string
            enum:
              - standard
              - sales
              - +releaseDate
              - '-releaseDate'
              - +itemPrice
              - '-itemPrice'
              - reviewCount
              - reviewAverage
            default: standard
          in: query
          name: sort
        - schema:
            type: string
            default: '1'
          in: query
          name: page
        - schema:
            type: integer
            enum:
              - '0'
              - '1'
            default: '0'
          in: query
          name: orFlag
        - schema:
            type: string
          in: query
          name: NGKeyword
