openapi: 3.0.0
info:
  title: BizToi
  version: '1.0'
  contact:
    name: BizToi
  description: BizToi API
servers:
  - url: 'http://localhost:8000'
paths:
  '/api/books':
    get:
      summary: Book List
      tags:
        - biztoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
              examples: {}
      description: すべての本を取得
      parameters: []
      operationId: Books
    parameters: []
    post:
      summary: ''
      responses:
        '200':
          description: OK
      description: 本の情報を作成する、本、問題、質問が作成されていない場合作成を行う
      operationId: BooksPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      tags:
        - biztoi
  '/api/books/{book_id}':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
    get:
      summary: GetToi
      tags:
        - biztoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Not Found
      description: 本情報を取得する
      operationId: GetBookId
  '/api/books/{book_id}/toi':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
    get:
      summary: GetToi
      tags:
        - biztoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Toi'
      description: 本に紐づく問を取得する
      operationId: GetBookToi
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Toi'
      operationId: PostToi
      description: Toi情報を作成する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Toi'
      tags:
        - biztoi
  '/api/books/{book_id}/questions':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
    get:
      summary: GetBookQuestion
      tags:
        - biztoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
      description: 本に紐づく質問一覧を取得する
      operationId: GetBookQuestions
    post:
      summary: ''
      responses:
        '200':
          description: OK
      operationId: PostQuestion
      description: 質問情報を作成する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      tags:
        - biztoi
  '/api/books/{book_id}/questions/{question_id}':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
      - schema:
          type: string
        name: question_id
        in: path
        required: true
    get:
      summary: GetBookQuestion
      tags:
        - biztoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
      description: 本に紐づく質問を取得する（Storeに存在しなかった場合）
      operationId: GetBookQuestion
  '/api/books/{book_id}/answers':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
    get:
      summary: GetAnswers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AnswerHead'
      description: 回答ヘッダー+回答データの取得
      operationId: GetAnswers
      tags:
        - biztoi
      parameters: []
  '/api/books/{book_id}/answers/{answer_id}':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
      - schema:
          type: string
        name: answer_id
        in: path
        required: true
    get:
      summary: GetAnswer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerHead'
      description: 回答ヘッダー+回答データの取得(Single)
      operationId: GetAnswer
      tags:
        - biztoi
      parameters: []
  '/api/books/{book_id}/answers/me':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
    get:
      summary: GetAnswersMe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerHead'
      description: 回答ヘッダー+回答データの取得(自ユーザ)
      operationId: GetAnswersMe
      tags:
        - biztoi
      parameters: []
    post:
      summary: PostAnswerHead
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerHead'
      description: 回答ヘッダー作成(自ユーザ)
      operationId: PostAnswerHead
      tags:
        - biztoi
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerHead'
  '/api/books/{book_id}/answers/me/{question_id}':
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        required: true
      - schema:
          type: string
        name: question_id
        in: path
        required: true
    get:
      summary: GetAnswerByQuestion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
      description: 質問に紐付いた回答データの取得（自ユーザ）
      operationId: GetAnswerByQuestion
      tags:
        - biztoi
      parameters: []
    post:
      summary: PostAnswerByQuestion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
      description: 質問に紐付いた回答データの作成（自ユーザ）
      operationId: PostAnswer
      tags:
        - biztoi
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerList'
  '/api/users/me':
    get:
      summary: User info
      tags:
        - biztoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BizToiUser'
      description: ユーザ情報
      parameters: []
      operationId: UserInfo
  '/api/auth/login':
    get:
      summary: Auth Login
      tags:
        - biztoi
      responses:
        '200':
          description: ''
        '303':
          description: See Other
      description: ログイン画面に遷移
      parameters:
        - schema:
            type: string
          in: query
          name: redirect_uri
          description: リダイレクト対象URL
          required: true
      operationId: AuthLogin
  '/api/auth/token':
    get:
      summary: Auth Get Token
      tags:
        - biztoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authorize'
      description: アクセストークン取得
      parameters:
        - schema:
            type: string
          in: query
          name: code
          description: AWS Cognitoより返却される認証コード
          required: true
      operationId: AuthGetToken
  '/api/favorite/books':
    post:
      summary: FavoriteBooks
      tags:
        - biztoi
      responses:
        '200':
          description: OK
      description: 本をお気に入りする
      parameters: []
      operationId: FavoriteBooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendLikeInfo'
    delete:
      summary: DeleteFavoriteBooks
      tags:
        - biztoi
      responses:
        '200':
          description: OK
      description: 本をお気に入り削除する
      parameters: []
      operationId: DeleteFavoriteBooks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendLikeInfo'
  '/api/likes/answers':
    post:
      summary: LikesAnswers
      tags:
        - biztoi
      responses:
        '200':
          description: OK
      description: 回答をいいねする
      parameters: []
      operationId: LikesAnswers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendLikeInfo'
    delete:
      summary: DeleteLikesAnswers
      tags:
        - biztoi
      responses:
        '200':
          description: OK
      description: 回答をいいね削除する
      parameters: []
      operationId: DeleteLikesAnswers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendLikeInfo'
components:
  schemas:
    Answer:
      title: Answer
      type: object
      description: ''
      properties:
        id:
          type: string
        orderId:
          type: string
          description: 順番を保持する項目
        answerHeadId:
          type: string
        questionId:
          type: string
        answer:
          type: string
        inserted:
          type: string
        modified:
          type: string
      required:
        - answerHeadId
        - questionId
        - orderId
        - answer
        - inserted
    AnswerHead:
      title: AnswerHead
      type: object
      properties:
        id:
          type: string
        bookId:
          type: string
        userId:
          type: string
        publishFlg:
          type: boolean
        inserted:
          type: string
        modified:
          type: string
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
        userInfo:
          $ref: '#/components/schemas/BizToiUser'
        likeInfo:
          $ref: '#/components/schemas/AnswerLikes'
      required:
        - id
        - userId
        - publishFlg
        - inserted
        - likeInfo
    Book:
      title: Book
      type: object
      properties:
        isbn:
          type: string
        title:
          type: string
        detail:
          type: string
        pictureUrl:
          type: string
        linkUrl:
          type: string
        authors:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            type: string
        favorite:
          type: boolean
      required:
        - isbn
        - detail
        - title
        - favorite
    Question:
      title: Question
      type: object
      properties:
        id:
          type: string
        patternId:
          type: integer
        orderId:
          type: integer
          description: 順番を保証した項目        
        title:
          type: string
        detail:
          type: string
        example:
          type: string
          description: 例文
        step:
          type: string
        answerType:
          type: string
          description: '0: OBJECTIVE, 1: GIST, 2: ACTION_PLAN'
        required:
          type: boolean
        nextQuestionId:
          type: string
          description: 次の質問を参照する項目
      required:
        - id
        - patternId
        - orderId
        - title
        - step
        - answerType
        - required
    Toi:
      title: Toi
      type: object
      properties:
        title:
          type: string
        detail:
          type: string
        publishFlg:
          type: boolean
      required:
        - title
        - detail
        - publishFlg
    BizToiUser:
      title: BizToiUser
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        pictureUrl:
          type: string
        nickname:
          type: string
        country:
          type: string
      required:
        - id
        - email
        - nickname
    Authorize:
      title: Authorize
      type: object
      properties:
        accessToken:
          type: string
      required:
        - accessToken
    AnswerList:
      title: AnswerList
      type: object
      properties:
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
      required:
        - answers
    AnswerLikes:
      title: AnswerLikes
      type: object
      properties:
        active:
          type: boolean
        sum:
          type: integer
        id:
          type: string
      required:
        - active
        - sum
        - id
    SendLikeInfo:
      title: SendLikeInfo
      type: object
      properties:
        id:
          type: string
        active:
          type: boolean
  securitySchemes: {}
