openapi: 3.0.0
info:
  title: BizToi
  version: '1.0'
  contact:
    name: BizToi
  description: BizToi API
servers:
  - url: 'http://localhost:8000/api'
paths:
  /books/create:
    parameters: []
    post:
      summary: Book Create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
              examples: {}
      description: 本の情報を作成する、本、問題、質問が作成されていない場合作成を行う
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      operationId: BookCreate
      tags: []
  /books:
    get:
      summary: Book List
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
              examples:
                example:
                  value:
                    - id: AAAABBBB
                      isbn: '1111100000'
                      detail: これはDaigoの本です。これはDaigoの本です。これはDaigoの本です
                      picture_url: 'http://books.google.com/books/content?id=NpBGDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'
                      link_url: 'https://google.com'
                      title: メンタリストDaiGoのポジティブ辞典
      description: すべての本を取得
      parameters: []
      operationId: Books
    parameters: []
  /users/me:
    get:
      summary: User info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      description: ユーザ情報
      parameters:
        - schema:
            type: string
          in: query
          name: code
          required: true
      operationId: UserInfo
  /auth/token:
    get:
      summary: Auth Get Token
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authorize'
      description: アクセストークン取得
      parameters:
        - schema:
            type: string
          in: query
          name: code
          description: AWS Cognitoより返却される認証コード
          required: true
      operationId: AuthGetToken
  /auth/login:
    get:
      summary: Auth Login
      tags: []
      responses:
        '200':
          description: ''
        '303':
          description: See Other
      description: ログイン画面に遷移する
      parameters:
        - schema:
            type: string
          in: query
          name: redirect_uri
          description: リダイレクト対象URL
          required: true
      operationId: AuthLogin
  '/toi/{book_id}':
    get:
      summary: Toi List
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Toi'
      description: 本に紐づく問題を取得する
      operationId: ToiList
    parameters:
      - schema:
          type: string
        name: book_id
        in: path
        description: ''
        required: true
  '/questions/{toi_id}':
    parameters:
      - schema:
          type: string
        name: toi_id
        in: path
        required: true
    get:
      summary: Qustions List
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Toi'
      description: 問題に紐づく質問の取得
      operationId: QustionsList
  '/answers/{toi_id}':
    parameters:
      - schema:
          type: string
        name: toi_id
        in: path
        required: true
    get:
      summary: Answers List
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerHead'
      description: 本と問題に紐づく回答の取得
      operationId: AnswersList
  /books/favorite:
    get:
      summary: Book Favorite List
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
      description: お気に入りの本を取得
      parameters: []
      operationId: BooksFavorite
    parameters: []
    post:
      summary: Book Favorite List Post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookFavorite'
      parameters: []
      description: 本をお気に入り登録する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookFavorite'
        description: ''
      operationId: BooksFavoritePost
      tags: []
    delete:
      summary: Book Favorite List Delete
      responses:
        '200':
          description: OK
      description: お気に入りを取り消しする
      operationId: BooksFavoriteDelete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookFavorite'
      tags: []
components:
  schemas:
    Answer:
      properties:
        id:
          type: string
        answer_head_id:
          type: string
        question_id:
          type: string
        picture_url:
          type: string
        answer:
          type: string
        inserted:
          type: string
        modified:
          type: string
      required:
        - answer_head_id
        - question_id
        - answer
        - inserted
      title: Answer
      type: object
    AnswerHead:
      title: AnswerHead
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        toi_id:
          type: string
        publish_flg:
          type: string
        inserted:
          type: string
        modified:
          type: string
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
      required:
        - id
        - user_id
        - toi_id
        - publish_flg
        - inserted
    Book:
      title: Book
      type: object
      required:
        - id
        - detail
        - title
      properties:
        id:
          type: string
        isbn:
          type: string
        detail:
          type: string
        picture_url:
          type: string
        link_url:
          type: string
        title:
          type: string
    BookFavorite:
      title: BookFavorite
      type: object
      properties:
        book_id:
          type: string
        favorite_id:
          type: string
    Question:
      title: Question
      type: object
      properties:
        modified:
          type: string
        inserted:
          type: string
        order_id:
          type: string
        required:
          type: string
        timing:
          type: string
        detail:
          type: string
        title:
          type: string
        toi_id:
          type: string
        id:
          type: string
      required:
        - id
        - toi_id
        - title
        - detail
        - timing
        - required
        - order_id
        - inserted
    Toi:
      title: Toi
      type: object
      required:
        - id
        - user_id
        - book_id
        - title
        - detail
        - public_flg
        - inserted
      properties:
        id:
          type: string
        user_id:
          type: string
        book_id:
          type: string
        picture_url:
          type: string
        title:
          type: string
        detail:
          type: string
        content:
          type: string
        public_flg:
          type: string
        inserted:
          type: string
        modified:
          type: string
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        picture_url:
          type: string
        name:
          type: string
      required:
        - id
        - name
        - email
    Authorize:
      title: Authorize
      type: object
      properties:
        access_token:
          type: string
      required:
        - access_token
  securitySchemes: {}
